### ISSUE TITLE
1.0.3 版本在 php7.4.8 可以编译成功，但是无法运行成功

### ISSUE THREAD

**Issue by xianganyall** [limingxinleo/php-jieba-ext#1]
在 php 7.2.16 版本，正常；

在 php 7.4.8 版本， make test 失败，如下错误：

PHP Warning:  PHP Startup: Unable to load dynamic library 'jieba.so' (tried: php-jieba-ext-1.0.3/modules/jieba.so (php-jieba-ext-1.0.3/modules/jieba.so: **undefined symbol: __cxa_pure_virtual**), 
php-jieba-ext-1.0.3/modules/jieba.so.so (php-jieba-ext-1.0.3/modules/jieba.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

-----
不知道能否看看是什么问题导致的?
系统： CentOS 7.8

**Comment by limingxinleo** [comment]
提供一个 Dockerfile 给我吧，我这没有 CentOS 7.8 的环境。。

7.4 在 alpine 下是正常的。

**Comment by xianganyall** [comment]
谢谢你的回复， 但是我这边也没有 dockerfile， 我这边是 直接本地的 PC电脑直接装的 CentOS 然后源码编译的php7.4.8，
你那边如果有空看看能否考虑抽空测试 源代码编译环境试试。

**Comment by xianganyall** [comment]
我发现 是因为编译的参数缺少 -lstdc++ , 对 Makefile 增加这个参数编译否就可以正常使用。

./jieba.la: $(shared_objects_jieba) $(JIEBA_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) **-lstdc++** $(COMMON_FLAGS) ........
---
为了让生成 Makefile 能编译还有  -lstdc++， 所以我编辑了 config.m4 增加了一行 CFLAGS="-lstdc++"
if test "$PHP_JIEBA" != "no"; then
  **CFLAGS="-lstdc++"**

-- 暂时这样就可以使用了，但是在php.ini 中配置时 jieba.so 模块必须在最后才可以，否则在jieba.so 之后的模块都失败。
extension=swoole.so
extension=redis.so
**extension=jieba.so**  他必须在最后， 怀疑可以 libstdc.so 有什么关系,如果在 swoole.so 之前则会报错： swoole.so (/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

**Comment by limingxinleo** [comment]
我也不是很懂。。我这边只用alpine。。。🤣

不过我司一直在用，我也监控过内存cpu，都是很稳定的。不过还是建议你单独开个docker，部署成为独立服务。

**Comment by xianganyall** [comment]
好的，多谢
